DEFINES  = -DDEBUG
#DEFINES += -DDEBUG_WAVE_CODEC
#DEFINES += -DDEBUG_WAVE_CODER
#DEFINES += -DDEBUG_WAVE_DECODER
#DEFINES += -DDEBUG_SAMPLE_CONVERSION

CFLAGS   += -O0 -g $(DEFINES)
CXXFLAGS += -O0 -g $(DEFINES)

$(TARGET): $(OBJECTS)
	$(CXX) $(LFLAGS) -o $@ $(OBJECTS)

include $(DEPS)